-- =============================================================================
-- schema_00_ddl_all_oracle.sql — 전체 구조 생성 DDL (Oracle 이식본)
--
--   원본        : schema_00_ddl_all.sql (MariaDB)
--   대상 DBMS   : Oracle Database 12c Release 1 (12.1.0.2) 이상
--   설계 근거   : docs/usecases/DB_00_데이터베이스구조설계_*.md
--   생성 대상   : 테이블 23개 + 인덱스 13개 + 주석
--
-- 실행 방법
--   sqlplus <user>/<password>@<tns> @schema_00_ddl_all_oracle.sql
--   자격증명은 이 파일에 쓰지 않는다(.env / FIRE_DB_* 환경변수 사용).
--
-- 선행 조건
--   1) DB 캐릭터셋이 AL32UTF8 이어야 한다. CHECK 제약과 기본값에 한글이 들어간다.
--        SELECT value FROM nls_database_parameters WHERE parameter='NLS_CHARACTERSET';
--   2) IDENTITY 컬럼은 12c 이상이다. 11g 이하는 파일 끝 부록 A(시퀀스+트리거)를 쓴다.
--   3) IS JSON 제약은 12.1.0.2 이상이다. 21c 이상이면 부록 B(네이티브 JSON)를 참고한다.
--
-- 원본과의 차이 (MariaDB → Oracle)
--   타입
--     VARCHAR(n)        → VARCHAR2(n CHAR)   문자 기준 길이. 한글이 바이트로 잘리지 않게 한다
--     TINYINT(1)        → NUMBER(1)          + CHECK IN (0,1)
--     TINYINT           → NUMBER(3)
--     SMALLINT          → NUMBER(5)
--     INT               → NUMBER(10)
--     BIGINT            → NUMBER(19)
--     DECIMAL(p,s)      → NUMBER(p,s)
--     DATETIME(3)       → TIMESTAMP(3)
--     DATETIME          → TIMESTAMP(0)
--     TEXT              → CLOB
--     JSON              → CLOB + CHECK (col IS JSON)
--     ENUM('a','b')     → VARCHAR2(n CHAR) + CHECK IN ('a','b')
--   구문
--     AUTO_INCREMENT            → GENERATED BY DEFAULT AS IDENTITY
--     DEFAULT CURRENT_TIMESTAMP → DEFAULT SYSTIMESTAMP
--     인라인 COMMENT            → COMMENT ON TABLE / COLUMN (문장 분리)
--     KEY ix_x (...)            → CREATE INDEX (문장 분리)
--     CHAR_LENGTH()             → LENGTH()
--     ENGINE=InnoDB CHARSET=... → 삭제
--     CREATE TABLE IF NOT EXISTS → CREATE TABLE (Oracle 23ai 미만은 미지원)
--                                  재실행하려면 파일 끝 부록 C 의 DROP 을 먼저 돌린다
--   컬럼명 변경 — 두 건뿐이며 이유가 다르다
--     ops_allocation_proposal.mode → alloc_mode
--         MODE 는 Oracle **예약어**다. "mode" 로 인용하면 애플리케이션 SQL 전부가
--         큰따옴표를 달아야 하므로 이름을 바꾸는 쪽이 낫다.
--     pred_cause_top3.`rank`       → rank_no
--         RANK 는 예약어는 아니나 분석함수명이라 혼동을 부른다. 원본도 백틱을 쓰고 있었다.
--     ※ 이식 시 애플리케이션 쿼리에서 이 두 컬럼명을 함께 바꿔야 한다.
--
-- 이식 시 주의 — Oracle DATE 는 시각을 포함한다
--   MariaDB DATE 는 날짜만 담지만 Oracle DATE 는 시·분·초를 함께 담는다.
--   target_date 는 pred_daily · ref_actual_* 의 **기본키 구성 컬럼**이므로,
--   시각이 섞여 들어오면 같은 날짜가 서로 다른 키가 되어 하루 251행 원칙(SC-006)이
--   조용히 깨진다. 적재 코드는 반드시 TRUNC 로 자정 기준으로 맞춘다.
--       INSERT ... VALUES (TRUNC(:target_date), ...)
--   조회도 등가비교가 안전하다:  WHERE target_date = TRUNC(:d)
--   원한다면 다음 제약을 추가해 강제할 수 있다(선택):
--       ALTER TABLE pred_daily ADD CONSTRAINT ck_pred_date_trunc
--             CHECK (target_date = TRUNC(target_date));
--
-- 실행 순서 (파일 내부가 이미 이 순서다)
--   1) ops_model_registry · ops_batch_run   2) ref_region_profile
--   3) ref_*  4) pred_*  5) ops_*  6) 신규 4
-- =============================================================================

SET DEFINE OFF


-- =============================================================================
-- 1) L4 뿌리 — 다른 계층이 참조하는 실행·모델 기록
-- =============================================================================

CREATE TABLE ops_model_registry (
  model_version     VARCHAR2(40 CHAR)  NOT NULL,
  model_id          VARCHAR2(4 CHAR)   NOT NULL,
  algorithm         VARCHAR2(60 CHAR),
  artifact_path     VARCHAR2(255 CHAR),
  train_data_range  CLOB,
  feature_list      CLOB,
  cv_metrics        CLOB,
  holdout_metrics   CLOB,
  acceptance_passed NUMBER(1)    DEFAULT 0 NOT NULL,
  code_commit       VARCHAR2(40 CHAR),
  is_active         NUMBER(1)    DEFAULT 0 NOT NULL,
  created_at        TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_model_registry PRIMARY KEY (model_version),
  CONSTRAINT ck_model_id       CHECK (model_id IN ('M0','M1','M5','M2a','M3','M4')),
  CONSTRAINT ck_model_passed   CHECK (acceptance_passed IN (0,1)),
  CONSTRAINT ck_model_active   CHECK (is_active IN (0,1)),
  CONSTRAINT ck_model_train_js CHECK (train_data_range IS JSON),
  CONSTRAINT ck_model_feat_js  CHECK (feature_list IS JSON),
  CONSTRAINT ck_model_cv_js    CHECK (cv_metrics IS JSON),
  CONSTRAINT ck_model_hold_js  CHECK (holdout_metrics IS JSON)
)
/
CREATE INDEX ix_model_active ON ops_model_registry (model_id, is_active)
/
COMMENT ON TABLE  ops_model_registry IS '모델 등록부 — SCR-07 · SCR-08 조회원'
/
COMMENT ON COLUMN ops_model_registry.feature_list      IS '입력 변수 + 관측가능성 등급'
/
COMMENT ON COLUMN ops_model_registry.cv_metrics        IS 'Expanding-window 5폴드'
/
COMMENT ON COLUMN ops_model_registry.holdout_metrics   IS '홀드아웃 2023 (1회 개봉)'
/
COMMENT ON COLUMN ops_model_registry.acceptance_passed IS '합격 판정 (SC-010)'
/

CREATE TABLE ops_batch_run (
  run_id              NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
  target_date         DATE         NOT NULL,
  started_at          TIMESTAMP(3) NOT NULL,
  finished_at         TIMESTAMP(3),
  status              VARCHAR2(8 CHAR)  DEFAULT '실행중' NOT NULL,
  regions_ok          NUMBER(5)    DEFAULT 0 NOT NULL,
  regions_failed      NUMBER(5)    DEFAULT 0 NOT NULL,
  failure_detail      CLOB,
  forecast_fetched_at TIMESTAMP(0),
  fallback_source     VARCHAR2(10 CHAR),
  drift_alerts        CLOB,
  CONSTRAINT pk_batch_run    PRIMARY KEY (run_id),
  CONSTRAINT ck_run_status   CHECK (status IN ('실행중','성공','부분실패','실패','폴백')),
  CONSTRAINT ck_run_fallback CHECK (fallback_source IN ('전일결과','M0기저율')),
  CONSTRAINT ck_run_fb_given CHECK (status <> '폴백' OR fallback_source IS NOT NULL),
  CONSTRAINT ck_run_fail_js  CHECK (failure_detail IS JSON),
  CONSTRAINT ck_run_drift_js CHECK (drift_alerts IS JSON)
)
/
CREATE INDEX ix_run_target ON ops_batch_run (target_date, run_id)
/
COMMENT ON TABLE  ops_batch_run IS '배치 실행 기록 — 실패를 조용히 넘기지 않는다 (FR-025)'
/
COMMENT ON COLUMN ops_batch_run.fallback_source IS 'CS-01 폴백 배너 사유'
/
COMMENT ON COLUMN ops_batch_run.failure_detail  IS '지역별 실패 요약(정규화본은 ops_batch_region_failure)'
/


-- =============================================================================
-- 2) L2 마스터 — 251개 시군구
-- =============================================================================

CREATE TABLE ref_region_profile (
  region_cd               VARCHAR2(24 CHAR) NOT NULL,
  sido                    VARCHAR2(30 CHAR) NOT NULL,
  sigungu                 VARCHAR2(30 CHAR) NOT NULL,
  area_km2                NUMBER(12,3),
  forest_ratio            NUMBER(8,4),
  timber_volume           NUMBER(14,2),
  population              NUMBER(10),
  households              NUMBER(10),
  pop_density             NUMBER(12,2),
  log_population          NUMBER(10,6),
  avg_station_distance_km NUMBER(8,2),
  CONSTRAINT pk_region_profile PRIMARY KEY (region_cd),
  CONSTRAINT ck_region_forest  CHECK (forest_ratio BETWEEN 0 AND 1),
  CONSTRAINT ck_region_pop     CHECK (population >= 0)
)
/
CREATE INDEX ix_region_sido ON ref_region_profile (sido)
/
COMMENT ON TABLE  ref_region_profile IS '시군구 마스터 251행 — 전 화면의 지역 축'
/
COMMENT ON COLUMN ref_region_profile.log_population          IS 'Poisson offset'
/
COMMENT ON COLUMN ref_region_profile.avg_station_distance_km IS '소방서 평균 거리'
/


-- =============================================================================
-- 3) L2 참조 — 배정·룩업·실적
-- =============================================================================

CREATE TABLE ref_station_map (
  region_cd     VARCHAR2(24 CHAR) NOT NULL,
  station_id    VARCHAR2(16 CHAR),
  assign_method VARCHAR2(8 CHAR) DEFAULT '관내' NOT NULL,
  grid_nx       NUMBER(5),
  grid_ny       NUMBER(5),
  is_proxy      NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_station_map    PRIMARY KEY (region_cd),
  CONSTRAINT ck_station_assign CHECK (assign_method IN ('관내','시도평균','산악','도서')),
  CONSTRAINT ck_station_proxy  CHECK (is_proxy IN (0,1))
)
/
COMMENT ON TABLE ref_station_map IS '시군구 → 관측지점 배정 (SCR-02 신뢰도 표기 근거)'
/

CREATE TABLE ref_region_cluster (
  region_cd     VARCHAR2(24 CHAR) NOT NULL,
  model_version VARCHAR2(40 CHAR) NOT NULL,
  cluster_id    NUMBER(3)         NOT NULL,
  cluster_label VARCHAR2(40 CHAR),
  CONSTRAINT pk_region_cluster PRIMARY KEY (region_cd, model_version)
)
/
COMMENT ON TABLE ref_region_cluster IS 'k=6 지역 군집 — 모델 버전별로 한 벌'
/

CREATE TABLE ref_risk_grade (
  model_version  VARCHAR2(40 CHAR)  NOT NULL,
  grade          VARCHAR2(8 CHAR)   NOT NULL,
  prob_lower     NUMBER(7,6)        NOT NULL,
  prob_upper     NUMBER(7,6)        NOT NULL,
  sort_order     NUMBER(3)          NOT NULL,
  color_token    VARCHAR2(32 CHAR),
  description_ko VARCHAR2(300 CHAR),
  CONSTRAINT pk_risk_grade    PRIMARY KEY (model_version, grade),
  CONSTRAINT ck_grade_name    CHECK (grade IN ('낮음','보통','높음','매우높음')),
  CONSTRAINT ck_grade_bounds  CHECK (prob_lower >= 0 AND prob_upper <= 1 AND prob_lower < prob_upper)
)
/
COMMENT ON TABLE ref_risk_grade IS '위험 등급 확률 경계 — SCR-01 · SCR-07'
/

CREATE TABLE ref_category_map (
  model_version     VARCHAR2(40 CHAR) NOT NULL,
  feature_name      VARCHAR2(40 CHAR) NOT NULL,
  raw_value         VARCHAR2(80 CHAR) NOT NULL,
  encoded_idx       NUMBER(10)        NOT NULL,
  is_unknown_bucket NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_category_map     PRIMARY KEY (model_version, feature_name, raw_value),
  CONSTRAINT ck_catmap_unknown   CHECK (is_unknown_bucket IN (0,1))
)
/
COMMENT ON TABLE ref_category_map IS '범주 인코딩 맵 — unknown 버킷으로 추론 실패를 막는다'
/

CREATE TABLE ref_actual_daily (
  target_date DATE              NOT NULL,
  region_cd   VARCHAR2(24 CHAR) NOT NULL,
  fire_count  NUMBER(5) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_actual_daily PRIMARY KEY (target_date, region_cd),
  CONSTRAINT ck_actual_count CHECK (fire_count >= 0)
)
/
CREATE INDEX ix_actual_region ON ref_actual_daily (region_cd, target_date)
/
COMMENT ON TABLE ref_actual_daily IS '사후 검증 기준 실적 — SCR-05'
/

CREATE TABLE ref_actual_spread (
  target_date DATE              NOT NULL,
  region_cd   VARCHAR2(24 CHAR) NOT NULL,
  fires       NUMBER(5) DEFAULT 0 NOT NULL,
  escalated   NUMBER(5) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_actual_spread   PRIMARY KEY (target_date, region_cd),
  CONSTRAINT ck_aspread_range   CHECK (escalated >= 0 AND escalated <= fires)
)
/
COMMENT ON TABLE ref_actual_spread IS '연소확대 실적 — SCR-05 확산 검증'
/

CREATE TABLE ref_actual_cause (
  target_date DATE              NOT NULL,
  region_cd   VARCHAR2(24 CHAR) NOT NULL,
  cause_class VARCHAR2(40 CHAR) NOT NULL,
  cnt         NUMBER(5) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_actual_cause PRIMARY KEY (target_date, region_cd, cause_class),
  CONSTRAINT ck_acause_cnt   CHECK (cnt >= 0)
)
/
COMMENT ON TABLE ref_actual_cause IS '발화요인 실적 — SCR-05 원인 검증'
/


-- =============================================================================
-- 4) L3 예측 — 배치 산출물
--    FR-022: 재산출이 이전 예측을 덮어쓰지 않는다 → PK 에 run_id 포함,
--            현재본은 is_current = 1
-- =============================================================================

CREATE TABLE pred_daily (
  target_date          DATE              NOT NULL,
  region_cd            VARCHAR2(24 CHAR) NOT NULL,
  run_id               NUMBER(19)        NOT NULL,
  is_current           NUMBER(1)    DEFAULT 1 NOT NULL,
  expected_count       NUMBER(10,6),
  occur_probability    NUMBER(7,6),
  occur_prob_raw       NUMBER(7,6),
  risk_grade           VARCHAR2(8 CHAR),
  risk_rank            NUMBER(5),
  spread_probability   NUMBER(7,6),
  longburn_probability NUMBER(7,6),
  expected_damage_load NUMBER(12,6),
  top_factors          CLOB,
  confidence           VARCHAR2(8 CHAR)  DEFAULT '정상' NOT NULL,
  data_status          VARCHAR2(10 CHAR) DEFAULT '정상' NOT NULL,
  source_model_version VARCHAR2(40 CHAR),
  created_at           TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_pred_daily     PRIMARY KEY (target_date, region_cd, run_id),
  CONSTRAINT ck_pred_current   CHECK (is_current IN (0,1)),
  CONSTRAINT ck_pred_grade     CHECK (risk_grade IN ('낮음','보통','높음','매우높음')),
  CONSTRAINT ck_pred_conf      CHECK (confidence IN ('정상','대리지점','폴백')),
  CONSTRAINT ck_pred_status    CHECK (data_status IN ('정상','최신아님','데이터없음')),
  CONSTRAINT ck_pred_prob      CHECK (occur_probability BETWEEN 0 AND 1),
  CONSTRAINT ck_pred_spread    CHECK (spread_probability BETWEEN 0 AND 1),
  CONSTRAINT ck_pred_factor_js CHECK (top_factors IS JSON),
  CONSTRAINT ck_pred_nodata    CHECK (data_status <> '데이터없음'
                                      OR (expected_count IS NULL AND occur_probability IS NULL))
)
/
CREATE INDEX ix_daily_rank    ON pred_daily (target_date, is_current, risk_rank)
/
CREATE INDEX ix_region_date   ON pred_daily (region_cd, target_date)
/
CREATE INDEX ix_current_grade ON pred_daily (is_current, target_date, risk_grade)
/
COMMENT ON TABLE  pred_daily IS '시군구x일 위험도 예측 — 하루 251행 (SC-006)'
/
COMMENT ON COLUMN pred_daily.is_current           IS '1=현재본, 0=이력'
/
COMMENT ON COLUMN pred_daily.spread_probability   IS 'M2a — 미산출 시 NULL (0 금지)'
/
COMMENT ON COLUMN pred_daily.longburn_probability IS 'M4 참고용 — 미산출 시 NULL'
/
COMMENT ON COLUMN pred_daily.expected_damage_load IS '기대 피해량 = 배분 수요 (FR-033)'
/
COMMENT ON COLUMN pred_daily.top_factors          IS 'CS-07 기여 요인 문장 3개 이상'
/

CREATE TABLE pred_feature_snapshot (
  target_date        DATE              NOT NULL,
  region_cd          VARCHAR2(24 CHAR) NOT NULL,
  run_id             NUMBER(19)        NOT NULL,
  features           CLOB,
  feature_grade      CLOB,
  forecast_issued_at TIMESTAMP(0),
  station_id         VARCHAR2(16 CHAR),
  psi                CLOB,
  CONSTRAINT pk_feature_snapshot PRIMARY KEY (target_date, region_cd, run_id),
  CONSTRAINT ck_snap_feat_js     CHECK (features IS JSON),
  CONSTRAINT ck_snap_grade_js    CHECK (feature_grade IS JSON),
  CONSTRAINT ck_snap_psi_js      CHECK (psi IS JSON)
)
/
COMMENT ON TABLE  pred_feature_snapshot IS '예측 입력 스냅샷 — SCR-02 "이 예측에 쓰인 값"'
/
COMMENT ON COLUMN pred_feature_snapshot.feature_grade IS 'A/B 만 허용 · C 사후한정 금지 (SC-016)'
/

CREATE TABLE pred_cause_top3 (
  target_date  DATE              NOT NULL,
  region_cd    VARCHAR2(24 CHAR) NOT NULL,
  run_id       NUMBER(19)        NOT NULL,
  rank_no      NUMBER(3)         NOT NULL,
  cause_class  VARCHAR2(40 CHAR) NOT NULL,
  probability  NUMBER(7,6)       NOT NULL,
  lift_vs_base NUMBER(9,4),
  CONSTRAINT pk_cause_top3  PRIMARY KEY (target_date, region_cd, run_id, rank_no),
  CONSTRAINT ck_cause_rank  CHECK (rank_no BETWEEN 1 AND 3),
  CONSTRAINT ck_cause_prob  CHECK (probability BETWEEN 0 AND 1)
)
/
COMMENT ON TABLE  pred_cause_top3 IS '발화 원인 후보 — SCR-02 이상 신호'
/
COMMENT ON COLUMN pred_cause_top3.rank_no      IS '원본 MariaDB 컬럼명은 rank (백틱 인용)'
/
COMMENT ON COLUMN pred_cause_top3.lift_vs_base IS '평시 대비 배율 — 2.0 이상만 화면 노출'
/


-- =============================================================================
-- 5) L4 운영 — 인력·제약·배분
-- =============================================================================

CREATE TABLE ops_deployment_status (
  region_cd  VARCHAR2(24 CHAR) NOT NULL,
  as_of      DATE              NOT NULL,
  on_duty    NUMBER(10),
  capacity   NUMBER(10),
  min_retain NUMBER(10),
  source     VARCHAR2(10 CHAR) DEFAULT '시스템추정' NOT NULL,
  CONSTRAINT pk_deployment_status PRIMARY KEY (region_cd, as_of),
  CONSTRAINT ck_deploy_source     CHECK (source IN ('담당자입력','시스템추정')),
  CONSTRAINT ck_deploy_retain     CHECK (min_retain <= capacity)
)
/
COMMENT ON TABLE  ops_deployment_status IS '지역별 인력 현황 — SCR-03 (미확보 시 비율 모드)'
/
COMMENT ON COLUMN ops_deployment_status.capacity   IS '정원 — 미확보 상태'
/
COMMENT ON COLUMN ops_deployment_status.min_retain IS '최소 잔류 — 미확보 상태'
/

CREATE TABLE ops_constraint (
  constraint_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  region_cd       VARCHAR2(24 CHAR),
  constraint_type VARCHAR2(12 CHAR) NOT NULL,
  value           NUMBER(10),
  is_active       NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT pk_ops_constraint    PRIMARY KEY (constraint_id),
  CONSTRAINT ck_constraint_type   CHECK (constraint_type IN ('정원상한','최소잔류','관할이탈금지')),
  CONSTRAINT ck_constraint_active CHECK (is_active IN (0,1))
)
/
CREATE INDEX ix_constraint_region ON ops_constraint (region_cd, is_active)
/
COMMENT ON TABLE  ops_constraint IS '운영 제약 — SCR-04 저장 차단 근거 (FR-036)'
/
COMMENT ON COLUMN ops_constraint.region_cd IS 'NULL 이면 전역 제약'
/

CREATE TABLE ops_allocation_proposal (
  proposal_id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  target_date         DATE       NOT NULL,
  run_id              NUMBER(19),
  alloc_mode          VARCHAR2(8 CHAR) DEFAULT 'ratio' NOT NULL,
  policy              CLOB,
  unmet_risk_before   NUMBER(16,6),
  unmet_risk_after    NUMBER(16,6),
  baseline_unmet_risk NUMBER(16,6),
  moved_total         NUMBER(14,4),
  staff_source        VARCHAR2(32 CHAR),
  created_at          TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_alloc_proposal   PRIMARY KEY (proposal_id),
  CONSTRAINT ck_proposal_mode    CHECK (alloc_mode IN ('ratio','absolute')),
  CONSTRAINT ck_proposal_pol_js  CHECK (policy IS JSON)
)
/
CREATE INDEX ix_proposal_date ON ops_allocation_proposal (target_date)
/
COMMENT ON TABLE  ops_allocation_proposal IS '배분안 헤더 — 같은 예측이어도 정책값이 다르면 답이 다르다'
/
COMMENT ON COLUMN ops_allocation_proposal.alloc_mode          IS '원본 MariaDB 컬럼명은 mode (Oracle 예약어)'
/
COMMENT ON COLUMN ops_allocation_proposal.policy              IS '{alpha,beta,delta} 산출에 쓴 정책값'
/
COMMENT ON COLUMN ops_allocation_proposal.unmet_risk_before   IS '현재 배치 그대로'
/
COMMENT ON COLUMN ops_allocation_proposal.unmet_risk_after    IS '권장안 적용 후'
/
COMMENT ON COLUMN ops_allocation_proposal.baseline_unmet_risk IS '균등 배치 기준선'
/
COMMENT ON COLUMN ops_allocation_proposal.moved_total         IS '권장안 실행 시 이동 인원'
/

CREATE TABLE ops_allocation_proposal_item (
  proposal_id           NUMBER(19)        NOT NULL,
  region_cd             VARCHAR2(24 CHAR) NOT NULL,
  demand_score          NUMBER(14,6),
  recommended_ratio     NUMBER(10,8),
  need_headcount        NUMBER(12,4),
  current_staff         NUMBER(12,4),
  recommended_headcount NUMBER(12,4),
  rationale             CLOB,
  CONSTRAINT pk_alloc_item     PRIMARY KEY (proposal_id, region_cd),
  CONSTRAINT ck_item_ratio     CHECK (recommended_ratio BETWEEN 0 AND 1),
  CONSTRAINT ck_item_rat_js    CHECK (rationale IS JSON)
)
/
COMMENT ON TABLE  ops_allocation_proposal_item IS '지역별 권장 배분 — SCR-03'
/
COMMENT ON COLUMN ops_allocation_proposal_item.demand_score          IS '수요 = 기대 피해량'
/
COMMENT ON COLUMN ops_allocation_proposal_item.need_headcount        IS '위험 비례 목표 need(r)'
/
COMMENT ON COLUMN ops_allocation_proposal_item.current_staff         IS '현재 인력 N(r)'
/
COMMENT ON COLUMN ops_allocation_proposal_item.recommended_headcount IS '권장 배치 x(r)'
/

CREATE TABLE ops_allocation_adjustment (
  adjustment_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  proposal_id          NUMBER(19)        NOT NULL,
  author_id            VARCHAR2(80 CHAR) NOT NULL,
  author_role          VARCHAR2(8 CHAR)  NOT NULL,
  created_at           TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  reason               CLOB              NOT NULL,
  constraint_violation CLOB,
  CONSTRAINT pk_alloc_adjustment PRIMARY KEY (adjustment_id),
  CONSTRAINT ck_adj_role         CHECK (author_role IN ('상황실','지휘','관리자','정책')),
  CONSTRAINT ck_adj_reason       CHECK (LENGTH(reason) > 0),
  CONSTRAINT ck_adj_viol_js      CHECK (constraint_violation IS JSON)
)
/
CREATE INDEX ix_adj_proposal ON ops_allocation_adjustment (proposal_id)
/
COMMENT ON TABLE  ops_allocation_adjustment IS '배분 조정 헤더 — SCR-04 (사유 없는 조정은 저장 불가 · FR-039)'
/

CREATE TABLE ops_allocation_adjustment_item (
  adjustment_id         NUMBER(19)        NOT NULL,
  region_cd             VARCHAR2(24 CHAR) NOT NULL,
  recommended_headcount NUMBER(10),
  adjusted_headcount    NUMBER(10),
  adjusted_ratio        NUMBER(10,8),
  CONSTRAINT pk_alloc_adj_item  PRIMARY KEY (adjustment_id, region_cd),
  CONSTRAINT ck_adjitem_nonneg  CHECK (adjusted_headcount >= 0)
)
/
COMMENT ON TABLE ops_allocation_adjustment_item IS '지역별 조정값 — SCR-04'
/


-- =============================================================================
-- 6) L4 신규 — 화면 설계에서 도출 (UI_02 SCR-08 · SCR-09)
-- =============================================================================

CREATE TABLE ops_model_acceptance (
  model_version  VARCHAR2(40 CHAR)  NOT NULL,
  criterion_code VARCHAR2(40 CHAR)  NOT NULL,
  gate_code      VARCHAR2(4 CHAR),
  criterion_desc VARCHAR2(200 CHAR) NOT NULL,
  threshold_expr VARCHAR2(80 CHAR)  NOT NULL,
  observed_value NUMBER(18,6),
  verdict        VARCHAR2(4 CHAR)   NOT NULL,
  sort_order     NUMBER(5) DEFAULT 0 NOT NULL,
  evaluated_at   TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_model_acceptance PRIMARY KEY (model_version, criterion_code),
  CONSTRAINT ck_accept_verdict   CHECK (verdict IN ('PASS','FAIL')),
  CONSTRAINT ck_accept_gate      CHECK (gate_code IN ('G18','G19','G20','G21'))
)
/
CREATE INDEX ix_accept_verdict ON ops_model_acceptance (verdict, model_version)
/
COMMENT ON TABLE  ops_model_acceptance IS '모델 합격 기준 판정표 — SCR-08'
/
COMMENT ON COLUMN ops_model_acceptance.criterion_code IS '예: recall_at_10'
/
COMMENT ON COLUMN ops_model_acceptance.threshold_expr IS '예: > 0.50'
/

CREATE TABLE ops_batch_step (
  run_id      NUMBER(19)        NOT NULL,
  step_no     NUMBER(3)         NOT NULL,
  step_code   VARCHAR2(10 CHAR) NOT NULL,
  status      VARCHAR2(6 CHAR)  NOT NULL,
  started_at  TIMESTAMP(3),
  finished_at TIMESTAMP(3),
  detail      CLOB,
  CONSTRAINT pk_batch_step   PRIMARY KEY (run_id, step_no),
  CONSTRAINT ck_step_code    CHECK (step_code IN ('개시판정','선행조건','기상확보','추론','적재마감')),
  CONSTRAINT ck_step_status  CHECK (status IN ('성공','실패','건너뜀','실행중')),
  CONSTRAINT ck_step_order   CHECK (step_no BETWEEN 1 AND 5),
  CONSTRAINT ck_step_dtl_js  CHECK (detail IS JSON)
)
/
COMMENT ON TABLE ops_batch_step IS '배치 실행 단계 타임라인 — SCR-09'
/

CREATE TABLE ops_batch_region_failure (
  run_id      NUMBER(19)         NOT NULL,
  region_cd   VARCHAR2(24 CHAR)  NOT NULL,
  stage       VARCHAR2(30 CHAR)  NOT NULL,
  reason      VARCHAR2(300 CHAR) NOT NULL,
  occurred_at TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_batch_reg_failure PRIMARY KEY (run_id, region_cd)
)
/
CREATE INDEX ix_bfail_region ON ops_batch_region_failure (region_cd, run_id)
/
COMMENT ON TABLE ops_batch_region_failure IS '지역별 배치 실패 사유 (정규화) — SCR-07 · SCR-09'
/

CREATE TABLE ops_feature_drift (
  run_id       NUMBER(19)        NOT NULL,
  feature_name VARCHAR2(40 CHAR) NOT NULL,
  psi          NUMBER(10,6)      NOT NULL,
  threshold    NUMBER(10,6) DEFAULT 0.25 NOT NULL,
  alert_flag   NUMBER(1)    DEFAULT 0 NOT NULL,
  measured_at  TIMESTAMP(3) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_feature_drift PRIMARY KEY (run_id, feature_name),
  CONSTRAINT ck_drift_alert   CHECK (alert_flag IN (0,1)),
  CONSTRAINT ck_drift_psi     CHECK (psi >= 0)
)
/
CREATE INDEX ix_drift_alert ON ops_feature_drift (alert_flag, run_id)
/
COMMENT ON TABLE ops_feature_drift IS '입력 분포 변화(PSI) — 현재 미측정'
/

COMMIT
/


-- =============================================================================
-- 부록 A. 11g 이하에서 IDENTITY 대체 (시퀀스 + 트리거)
--   12c 이상이면 필요 없다. 3개 테이블(run_id · constraint_id · proposal_id ·
--   adjustment_id)에 대해 아래 형태를 반복한다.
-- =============================================================================
-- CREATE SEQUENCE seq_batch_run START WITH 1 INCREMENT BY 1 NOCACHE;
-- CREATE OR REPLACE TRIGGER trg_batch_run_bi
--   BEFORE INSERT ON ops_batch_run FOR EACH ROW
--   WHEN (NEW.run_id IS NULL)
-- BEGIN
--   :NEW.run_id := seq_batch_run.NEXTVAL;
-- END;
-- /

-- =============================================================================
-- 부록 B. 21c 이상 — 네이티브 JSON 타입
--   CLOB + IS JSON 대신 JSON 타입을 쓰면 저장·조회가 더 효율적이다.
--     ALTER TABLE pred_daily MODIFY (top_factors JSON);
--   단 12c~19c 에서는 지원되지 않으므로 이 파일은 CLOB 을 기본으로 둔다.
-- =============================================================================

-- =============================================================================
-- 부록 C. 재실행용 DROP (역순 — 참조가 걸리면 CASCADE CONSTRAINTS 를 쓴다)
-- =============================================================================
-- DROP TABLE ops_feature_drift              CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_batch_region_failure       CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_batch_step                 CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_model_acceptance           CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_allocation_adjustment_item CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_allocation_adjustment      CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_allocation_proposal_item   CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_allocation_proposal        CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_constraint                 CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_deployment_status          CASCADE CONSTRAINTS PURGE;
-- DROP TABLE pred_cause_top3                CASCADE CONSTRAINTS PURGE;
-- DROP TABLE pred_feature_snapshot          CASCADE CONSTRAINTS PURGE;
-- DROP TABLE pred_daily                     CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ref_actual_cause               CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ref_actual_spread              CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ref_actual_daily               CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ref_category_map               CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ref_risk_grade                 CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ref_region_cluster             CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ref_station_map                CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ref_region_profile             CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_batch_run                  CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ops_model_registry             CASCADE CONSTRAINTS PURGE;

-- =============================================================================
-- 끝. 생성 확인:
--   SELECT table_name FROM user_tables
--    WHERE table_name LIKE 'REF\_%' ESCAPE '\'
--       OR table_name LIKE 'PRED\_%' ESCAPE '\'
--       OR table_name LIKE 'OPS\_%' ESCAPE '\' ORDER BY table_name;
-- =============================================================================
